# Uncomment the next line to define a global platform for your project
 platform :ios, '14.0'

target 'HW2.9' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Spring', :git => 'https://github.com/MengTo/Spring.git'

end
